### ISSUE TITLE
Is this still being developed/bug fixed?

### ISSUE THREAD

**Issue by tchoulihan** [mgodave/barge#80]
Hey, I'm thinking of creating a library based on barge, and just want to make sure its still being kept up, before I proceed.

Also, where is the snapshot repo? ClusterConfig isn't availble with 0.1.0-alpha1

**Comment by abailly** [comment]
Hi Tyler
No there has not been any serious new development on barge since last year.
Current features set is limited but stable. Contributions are of course
welcomed !

Regards

Arnaud

Le mardi 21 avril 2015, Tyler Houlihan <notifications@github.com> a écrit :

> Hey, I'm thinking of creating a library based on barge, and just want to
> make sure its still being kept up, before I proceed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgodave/barge/issues/80>.
>


-- 
-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by tchoulihan** [comment]
Alright, thanks.

**Comment by mgodave** [comment]
What Arnaud said. I wish I had more time but I'll happily look at contributions.

**Comment by justinsb** [comment]
Facebook are open-sourcing a version of HBase that uses Raft for consensus.  I think that seems likely to be a feature-complete implementation of Raft in Java before barge (i.e. I think it already incorporates dynamic membership & log compaction).

**Comment by mgodave** [comment]
(+1)
